name: Javelin of Lightning {i}
automation:
  - type: text
    text: >-
      This javelin is a magic weapon. When you hurl it and speak its command
      word, it transforms into a bolt of lightning, forming a line 5 feet wide
      that extends out from you to a target within 120 feet. Each creature in
      the line excluding you and the target must make a DC 13 Dexterity saving
      throw, taking 4d6 lightning damage on a failed save, and half as much
      damage on a successful one. The lightning bolt turns back into a javelin
      when it reaches the target. Make a ranged weapon attack against the
      target. On a hit, the target takes damage from the javelin plus 4d6
      lightning damage.


      The javelin's property can't be used again until the next dawn. In the meantime, the javelin can still be used as a magic weapon.


      Proficiency with a javelin allows you to add your proficiency bonus to the attack roll for any attack you make with it.
  - type: counter
    counter: Javelin of Lightning {i}
    amount: "1"
    allowOverflow: null
    errorBehaviour: null
  - type: target
    target: all
    effects:
      - type: condition
        condition: targetIndex == 0
        onTrue:
          - type: attack
            hit:
              - type: damage
                damage: 1d6[magical piercing] + 4d6[lightning]
                overheal: null
            miss: []
            attackBonus: strengthMod + proficiencyBonus
        onFalse:
          - type: save
            stat: dex
            fail:
              - type: damage
                damage: 4d6[lightning]
                overheal: null
            success:
              - type: damage
                damage: 4d6[lightning] / 2
                overheal: null
            dc: "13"
        errorBehaviour: "false"
_v: 2
activation_type: 1